#!/bin/bash

# Automagic script to launch doMast on many regulators/genomes

if [ "$#" -lt 5 ]; then
    echo 'autoMast MOTIF_DIR FASTA_DIR BFILE_DIR GENBANK_DIR RESULTS_DIR'
    exit 65
fi

MOTIF_DIR=$1
FASTA_DIR=$2
BFILE_DIR=$3
GENBANK_DIR=$4
RESULTS_DIR=$5

for reg in $(ls -d $MOTIF_DIR/*/)
do
    count=0
    regulator=$(echo $reg | awk 'BEGIN {FS = "/"}; {print ( $(NF-1) )}')
	for meme in $(ls -d $reg/*/)
	do
	    let "count += 1"
	    ./doMast $meme/meme.txt $FASTA_DIR $BFILE_DIR $GENBANK_DIR $RESULTS_DIR $regulator'_'$count
	done
done
