#!/usr/bin/python

import sys

if len(sys.argv) < 3:
	print 'USAGE: compareLiterature PRED LIT'
	sys.exit(1)

pred, lit = sys.argv[1:3]

p = set()
for l in open(pred):
	p.add(l.strip())

l = set()
for j in open(lit):
	l.add(j.strip())

print '\t'.join([str(len(p.intersection(l))), str(len(p.difference(l))), str(len(l.difference(p)))])
