#!/bin/bash

# Given a directory containing only fasta files, produces one
# background file for each genome
# Produces a 3-order Markov background

if [ "$#" -lt 1 ]; then
    echo 'doBfile FASTA_DIR'
    exit 65
fi

FASTA_DIR=$1

for i in $(ls $FASTA_DIR | grep ".fa")
do
    strain=$(echo $i | awk 'BEGIN {FS = "."};{print $1}')
    echo $strain
    cat $FASTA_DIR/$i | fasta-get-markov -m 3 > $strain.ntfreq
done
