#!/bin/bash

# Given a motif file (meme.txt) and a directory full of genomes in fasta format
# launches the biopython motif search on each genome

if [ "$#" -lt 5 ]; then
    echo 'doBiopy MOTIF_FILE FASTA_DIR GENBANK_DIR RESULTS_DIR REGULATOR_NAME'
    exit 65
fi

MOTIF_FILE=$1
FASTA_DIR=$2
GENBANK_DIR=$3
RESULTS_DIR=$4
REGULATOR_NAME=$5

for i in $(ls $FASTA_DIR)
do
	org=$(echo $i | awk 'BEGIN { FS = "." } ; {print $1}')
	mkdir $RESULTS_DIR/$org'_'$REGULATOR_NAME > /dev/null
	./searchBiopy $MOTIF_FILE $FASTA_DIR/$i > $RESULTS_DIR/$org'_'$REGULATOR_NAME'/hits.txt'

	./parseBiopy -l -o $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_orientation.tab'
	./parseBiopy -l $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_noorientation.tab'
done
