#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo 'doGenomicDist ALIGNMENT'
    exit 65
fi

die () {
	exit 1
}

./fasta2Nexus $1 || die
./nexus2MrBayes $1.nex || die
mb $1.nex > $1.log || die
./mrBayes2Newick $1.nex.con || die
./treeDist $1.nex.con.nwk > $1.dist || die


