#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo 'doGenomicDist ALIGNMENT'
    exit 65
fi

./fasta2Nexus $1
./nexus2MrBayes $1.nex
mb $1.nex > $1.log
./mrBayes2Newick $1.nex.con
./treeDist $1.nex.con.nwk > $1.dist


