#!/bin/bash

# Given a motif file (meme.hmm) and a directory full of genomes in fasta format
# launches nhmmer on each genome

if [ "$#" -lt 5 ]; then
    echo 'doHMM MOTIF_FILE FASTA_DIR GENBANK_DIR RESULTS_DIR REGULATOR_NAME'
    exit 65
fi

MOTIF_FILE=$1
FASTA_DIR=$2
GENBANK_DIR=$3
RESULTS_DIR=$4
REGULATOR_NAME=$5

for i in $(ls $FASTA_DIR)
do
	org=$(echo $i | awk 'BEGIN { FS = "." } ; {print $1}')
	mkdir $RESULTS_DIR/$org'_'$REGULATOR_NAME > /dev/null

    nhmmer --max -E 100 --tblout $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $MOTIF_FILE $FASTA_DIR/$i > /dev/null

	./parseHMM -l -o $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $MOTIF_FILE $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_orientation.tab'
	./parseHMM -l $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $MOTIF_FILE $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_noorientation.tab'
done
