#!/bin/bash

# Given a motif file (meme.txt) and a directory full of geneomes in fasta format
# launches mast on each genome

if [ "$#" -lt 3 ]; then
    echo 'doMast MOTIF_FILE FASTA_DIR REGULATOR_NAME'
    exit 65
fi

MOTIF_FILE=$1
FASTA_DIR=$2
REGULATOR_NAME=$3

for i in $(ls $FASTA_DIR)
do
	org=$(echo $i | awk 'BEGIN { FS = "." } ; {print $1}')
	mast $MOTIF_FILE $FASTA_DIR/$i -oc $org'_'$REGULATOR_NAME
	mast $MOTIF_FILE $FASTA_DIR/$i -oc $org'_'$REGULATOR_NAME -hit_list > $org'_'$REGULATOR_NAME/hits.txt
done
