#!/bin/bash

# Given a motif file (meme.txt) and a directory full of genomes in fasta format
# launches mast on each genome

if [ "$#" -lt 5 ]; then
    echo 'doRSAT MOTIF_FILE FASTA_DIR GENBANK_DIR RESULTS_DIR REGULATOR_NAME'
    exit 65
fi

MOTIF_FILE=$1
FASTA_DIR=$2
GENBANK_DIR=$3
RESULTS_DIR=$4
REGULATOR_NAME=$5

for i in $(ls $FASTA_DIR)
do
	org=$(echo $i | awk 'BEGIN { FS = "." } ; {print $1}')
	mkdir $RESULTS_DIR/$org'_'$REGULATOR_NAME > /dev/null
	matrix-scan -m $MOTIF_FILE -matrix_format meme -i $FASTA_DIR/$i -bginput -markov 3 -return sites -o $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt -quick -n skip -uth pval 0.00001
	./parseRSAT -l -t 1e-6 -o $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_orientation.tab'
	./parseRSAT -l -t 1e-6 $RESULTS_DIR/$org'_'$REGULATOR_NAME/hits.txt $GENBANK_DIR/$org.gbk $REGULATOR_NAME > $RESULTS_DIR/$org'_'$REGULATOR_NAME'_noorientation.tab'
done
