#!/usr/bin/python
'''
Converts mast hits P-value into E-values, considering the length of the motif
and the length of the genome.
'''

import sys
from Bio import SeqIO

if len(sys.argv) < 3:
    print 'USAGE: ./getMastEvalue HITS_FILE FASTA_FILE'
    sys.exit(1)

infile = sys.argv[1]
seqfile = sys.argv[2]

dsize = 0
for s in SeqIO.parse(seqfile, 'fasta'):
    dsize += len(s)

for l in open(infile):
    if l.startswith('#'):continue
    s = l.strip().split()

    ev = float(s[5]) * ( int(s[3]) - int(s[2]) ) * dsize
    
    s[5] = str(ev)
    
    sys.stdout.write( ' '.join(s) + '\n' )
