#!/usr/bin/python

# IMPORTANT! we assume that MrBayes produces a *.con file
# Some newer versions produce a different tree file

import sys

if len(sys.argv) < 2:
    print 'USAGE: ./mrBayes2Newick CON_FILE'
    sys.exit(1)

infile = sys.argv[1]

trigger = 'tree con_50_majrule = '

b = True
nwk = None

for l in open(infile):
    l = l.strip()

    # First occurrence, skip
    if not l.startswith(trigger):
        continue
    elif b:
        b = False
        continue
    else:
        nwk = l.split(trigger)[1]

if nwk is None:
    raise ValueError('No nwk tree!')

f = open('%s.nwk'%infile, 'w')
f.write('%s\n'%nwk)
f.close()
 
