#!/usr/bin/python
'''
Read the tabular output of nhmmer, and check which hits are in the upstream region
of a gene based on a GenBank file
'''

__author__ = "Marco Galardini"

from Bio import SeqIO
from regtools import *

################################################################################
# Read options

def getOptions():
    import argparse

    # create the top-level parser
    description = ("Parse the tabular output of nhmmer, a GenBank file and a MEME motif file, "+
                    "providing the list of hits found in gene upstream regions")
    parser = argparse.ArgumentParser(description = description)
    parser.add_argument('nhmmer', action="store",
                            help='RSAT tabular file')
    parser.add_argument('genome', action="store",
                            help='Genome GenBank file')
    parser.add_argument('motif', action="store",
                            help='MEME motif file')
    parser.add_argument('regulator', action="store",
                            help='Regulator name')
    parser.add_argument('-u', '--upstream', action='store',
                        type=int,
                        default=400,
                        help='Upstream region size [Default: 400bp]')
    parser.add_argument('-d', '--downstream', action='store',
                        type=int,
                        default=100,
                        help='Upstream region size [Default: 100bp]')
    parser.add_argument('-t', '--threshold', action='store',
                        type=float,
                        default=10,
                        help='p-value threshold [Default: 10]')
    parser.add_argument('-o', '--order', action="store_true",
            default=False,
            dest='order',
            help='The motif has to be found in forward with the gene (not for palindromic motifs)')
    parser.add_argument('-f', '--fasta', action="store_true",
            default=False,
            dest='fasta',
            help='Output in FASTA format')
    parser.add_argument('-l', '--linear', action="store_true",
                            default=False,
                        help='Linear or draft genome')
    parser.add_argument('-a', '--all', action="store_true",
                    dest='all',
                    default=False,
                help='Save ALL upstream regions (not considering genes overlaps and -u option)')
    parser.add_argument('-r', '--header', action="store_true",
                    dest='header',
                    default=False,
                help='Print explanatory header (incompatible with -f)')
    
    return parser.parse_args()

################################################################################
# Classes

class HMM(object):
    def __init__(self, dna, strand, mname, start, stop, score, evalue):
        self.dna = dna
        self.strand = strand
        self.mname = mname
        self.start = int(start)
        self.stop = int(stop)
        self.score = float(score)
        self.evalue = float(evalue)

################################################################################
# Functions

def parseHMM(fname, motifLen, threshold=10):
    '''
    Generator to relevant lines of a HMM tabular output
    Returns HMM objects
    '''
    for l in open(fname):
        if l.lstrip().startswith('#'):continue
        
        l = l.strip()
        while '  ' in l:
            l=l.replace('  ', ' ')
        
        (dna, x1,x2,x3, hmmfrom, hmmto, start, stop,
        x4,x5,x6, strand, evalue, score, x7,x8) = l.split()
        
        start, stop = sorted([int(start), int(stop)])

        if float(evalue) > threshold:continue
        if int(hmmto) - int(hmmfrom) + 1 != motifLen:continue
        
        yield HMM(dna, strand, dna, start, stop, score, evalue)
        
def getUpstreams(record, b_up=400, b_down=100, is_circ=True, all_up=False):
    genes=get_genes(record)
    if len(genes)==0:
        return []
    whole_seq=get_whole_genome_seq(record)
    if not all_up:
        upstreams=get_all_upstreams(genes,whole_seq, b_up, b_down, is_circ)
    else:
        upstreams=get_all_upstreams_all(genes,whole_seq, b_up, b_down, is_circ)
    return upstreams

################################################################################
# Main

if __name__ == "__main__":
    options = getOptions()

    # Read the input motif (we need to know its length)
    for l in open(options.motif):
        l=l.strip()
        if 'LENG  ' in l:
            mLen=int(l.lstrip('LENG  ')))

    hits = {}
    for m in parseHMM(options.nhmmer, mLen, options.threshold):
        if m.dna not in hits:
            hits[m.dna] = set()
        hits[m.dna].add(m)
       
    i = 0
    
    if options.header:
        print '#' + '\t'.join([str(x) for x in ['locus_tag',
                                          'dna_id', 'dna_strand',
                                          'dna_start', 'dna_stop',
                                          'motif_strand', 'motif_start',
                                          'motif_stop',
                                          'motif_seq', 'method',
                                          'evalue', 'threshold',
                                          'regulator_name']])
    
    for s in SeqIO.parse(open(options.genome), 'genbank'):
        if s.id not in hits:
            # NHMMer trims the '.1' from the id of complete genomes
            # We assume that every sequence is at its first version
            if s.id.rstrip('.1') not in hits:
                continue
            # End of the ugly exception
        
        dups = {}
        upstream = getUpstreams(s, options.upstream, options.downstream,
                                not options.linear, options.all)
        for u in upstream:
            dups[u.name] = u
        
        for m in sorted(hits[s.id.rstrip('.1')], key=lambda x: x.start):
            for f in filter(lambda x: x.type == 'CDS', s.features):
                gname = f.qualifiers['locus_tag'][0]
                
                if f.strand == 1:
                    if (m.start > (dups[gname].start) and
                           m.stop < (dups[gname].end)):
                        if options.order and m.strand == '-':continue
                        
                        if m.strand == '-':
                            strand = '-'
                        else:
                            strand = '+'
                        
                        start = m.start - f.location.start
                        stop = m.stop - f.location.start
                        
                        if m.strand == '+':
                            seq = s[m.start  -1:m.stop ].seq
                        else:
                            seq = s[m.start  -1:m.stop ].seq.reverse_complement()
                        
                        if options.fasta:
                            print '>%d'%i
                            print seq
                            i += 1
                        else:
                            print '\t'.join([str(x) for x in [gname,
                                                  s.id, m.strand,
                                                  m.start, m.stop,
                                                  strand, start, stop,
                                                  seq, 'nhmmer',
                                                  m.evalue, options.threshold,
                                                  options.regulator]])
                else:
                    if (m.start > (dups[gname].start) and
                           m.stop < (dups[gname].end)):
                        if options.order and m.strand == '+':continue
                            
                        if m.strand == '+':
                            strand = '-'
                        else:
                            strand = '+'
                        
                        start = f.location.end - m.stop
                        stop = f.location.end - m.start
                        
                        if m.strand == '+':
                            seq = s[m.start  -1:m.stop ].seq
                        else:
                            seq = s[m.start  -1:m.stop ].seq.reverse_complement()
                        
                        if options.fasta:
                            print '>%d'%i
                            print seq
                            i += 1
                        else:
                            print '\t'.join([str(x) for x in [gname,
                                                  s.id, m.strand,
                                                  m.start, m.stop,
                                                  strand, start, stop,
                                                  seq, 'nhmmer',
                                                  m.evalue, options.threshold,
                                                  options.regulator]])
        
    
