#!/usr/bin/python

import sys

if len(sys.argv) < 3:
	print 'USAGE: ./runCompare INDIR FILE[S]'
	sys.exit(1)

indir = sys.argv[1]
files = sys.argv[2:]

import os
import subprocess

for f in files:
	s = os.path.split(f)[-1].split('_')
	
	reg = s[0].split('.')[0]
	org = '_'.join(s[1:]).split('.')[0]

	#org = os.path.split(f)[-1].split('_')[0]
	#reg = os.path.split(f)[-1].split('_')[1].split('.')[0]

	f1 = '%s.tab'%reg
        f2 = '%s_a.tab'%reg

	f1a = os.path.join(indir, f1)
	f2a = os.path.join(indir, f2)

	#print f, f1a, f2a

	if f1 in os.listdir(indir):
		proc = subprocess.Popen('./compareLiterature %s %s'%(f, f1a),shell=(sys.platform!="win32"),
                    stdin=subprocess.PIPE,stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE)
		out = proc.communicate()
		
		core, pred_only, lit_only = out[0].strip().split('\t')
		print '\t'.join([org, reg, core, pred_only, lit_only])

	if f2 in os.listdir(indir):
                proc = subprocess.Popen('./compareLiterature %s %s'%(f, f2a),shell=(sys.platform!="win32"),
                    stdin=subprocess.PIPE,stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE)
                out = proc.communicate()

                core, pred_only, lit_only = out[0].strip().split('\t')
                print '\t'.join([org, reg, core, pred_only, lit_only])
